### ISSUE TITLE
Duplicate menu entries are still an issue with Firefox

### ISSUE THREAD

**Issue by HyerrDoktyer** [aleho/gnome-shell-volume-mixer#130]
Hi, I am aware of the older issues (https://github.com/aleho/gnome-shell-volume-mixer/issues/78 ect ...) but I thought it would be best to make something new given how long it has been.

This is not an issue which is isolated to this project, Windows users have been grappling with this for years (https://bugzilla.mozilla.org/show_bug.cgi?id=1430907) and it seems to pop back up every time it's 'fixed'.

Any ideas about what can be done regarding this? It's quite frustrating because ultimately only a single one of these sliders controls my audio source and I need to go through all of them individually to find the correct one, of which there are often multiple dozen.

![annoying!](https://user-images.githubusercontent.com/34185288/99254589-80ef3b00-2862-11eb-944c-e09967f2af08.png)

**Comment by aleho** [comment]
It might in theory be possible to group sliders by application name with a synchronized slider controlling all of them, but that would introduce yet another misuse of the status menu, leading to many hacks needed to make it look good (especially since there's no concept of submenu items holding submenus that I'm aware of).

And then there's the question of "how many items to start grouping" and how to identify apps.

As you can see, even GNOME Audio settings doesn't group applications:
![Firefox streams in GNOME Audio settings](https://user-images.githubusercontent.com/138721/99257727-c6d2e180-2817-11eb-9418-023013103c19.png).


Ultimately I think that's beyond my goal of this extension. I'm not saying I'm opposed to a nice implementation if someone steps up and provides a PR. Currently there are a few nasty bugs that I should address first (actually GNOME/PulseAudio weirdness) and they've been occupying all my spare time so far.
