### ISSUE TITLE
[gnome-shell 3.18] latest version doesn't look so great

### ISSUE THREAD

**Issue by NForce** [aleho/gnome-shell-volume-mixer#38]
After latest commits main applet slider shrank and doesn't look too good now. Screenshot is attached
![screenshot from 2015-10-07 22-26-32](https://cloud.githubusercontent.com/assets/685165/10348674/2d9cb19c-6d43-11e5-9e3d-b7b6cc194d53.png)
I am using gnome shell version 3.18. It looked normal before updating applet

**Comment by cyberalex4life** [comment]
Just edit stylesheet.css and change 170px from the section:

/* since 3.18 */
.masterslider.smaller .masterlabel,
.masterslider.smaller .slider {
    width: 170px;
}
to 253px like the previous section

**Comment by NForce** [comment]
Thanks, thought of doing this, but waited for a possible fix from upstream. But now I see that this might not get any attention, so I edited stylesheet like you said. FYI, 258px appears to be too much, 232px did the trick.

**Comment by cyberalex4life** [comment]
Depends on your setup, it's a small fix, and maybe it's too much to fix for now (if things are different from one desktop to another), if you have to find the core of this.

**Comment by aleho** [comment]
The real problem here is that I can't seem to find consistent values across distributions.

Even in Fedora 23 pre-release and on Debian/experimental the theme was different than in some point release later.

I also haven't found a way to programatically determine widths. If anyone comes up with a solution, I'm happy to merge it. This is an open-source project after all.
