### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by aleho** [aleho/gnome-shell-volume-mixer#7]
karatedebili:
would it be possible to implement a shortcut on the keyboard to toggle output between soundcards?

**Comment by deBili** [comment]
thank you so much for this! :) i only discovered it now that you made this happen!!

one thing i'd like to ask however...when switching the outputs, an OSD popup notifies me which output is selected, similar to when changing volume with media keys... But it displays hardware names, instead of how i've labeled the outputs. in the volume menu of your extension, the outputs are labeled nicely with labels (renamed by me by enabling module-device-manager and renaming each soundcard via pavucontrol) but on the OSD popup "old" hardware names are displayed. 
This is just a detail and i have no clue about if this can be fixed from within the extension or this is unchangable gnome bahavior... but perhaps for you it's an easy fix, to a non-programmer like me it seems like on the 'Devices' tab of the extensions' settings, there could be an 'edit' button down next to +- for renaming the selected outputs (as the list on the left also shows hardware names...) :P 

Thanks again and keep up the good work!!
