### ISSUE TITLE
short slider for bluetooth device "4D BOX"

### ISSUE THREAD

**Issue by buxit** [aleho/gnome-shell-volume-mixer#71]
when connected to the bluetooth speaker named "4D BOX", a slider appears that is a lot shorter than all other sliders. see the screenshots below.

![screenshot from 2017-10-23 12-33-43](https://user-images.githubusercontent.com/1142965/31885735-d7e579cc-b7f1-11e7-8a51-e8c4ad1432d5.png)
![screenshot from 2017-10-23 12-31-43](https://user-images.githubusercontent.com/1142965/31885736-d7ffd416-b7f1-11e7-92aa-00855a1ff9fd.png)

**Comment by ferdnyc** [comment]
I'm seeing the same thing with my bluetooth headphones; it's always been that way since I started using the extension, and the behavior is the same even with the newest e.g.o version (just updated 5-10 minutes ago).

Interestingly, the length of my headphones' slider looks _different_ than what @buxit is getting — it almost looks like it's related to the length of the **label** for the device?

![screenshot from 2017-10-29 00-11-44](https://user-images.githubusercontent.com/538020/32140644-62f73514-bc3e-11e7-9c9a-d0611fcce955.png)

**Comment by aleho** [comment]
Is this still a problem with the latest releases (0.13, 0.14)?

**Comment by ferdnyc** [comment]
I believe so; my screenshot was taken with the latest e.g.o update just released yesterday, it's version 18 in their `metadata.json`.

**Comment by aleho** [comment]
Your screenshots don't look like the latest two versions though. The slider moved below icon and label.

**Comment by ferdnyc** [comment]
Like I said, it's the latest e.g.o version, I don't see a way to easily map that to your version numbering, but I assume it's definitely _not_ the version 0.14 that was released today since their approval process isn't that fast. (Plus, I installed it last night.)

I guess I'll pull the HEAD from github, install that, and see if anything changes...

**Comment by ferdnyc** [comment]
Nope, looks like it will clear up with 0.14. Cool. 
![screenshot from 2017-10-29 13-40-23](https://user-images.githubusercontent.com/538020/32146497-d543d1e8-bcae-11e7-88da-a4ee385fef0c.png)

**Comment by aleho** [comment]
It acutally looks like that in 0.13.0 as well, which should be live (if I'm not mistaken).

The releases page has all the versions I upload to the extensions repo.
