### ISSUE TITLE
Shortcut switch ignores USB Wireless Headset

### ISSUE THREAD

**Issue by azatoth** [aleho/gnome-shell-volume-mixer#79]
I've a Logitech G533 Wireless headset and I've added it to the device list:
![screenshot from 2018-01-06 14-17-51](https://user-images.githubusercontent.com/146477/34640084-713f069e-f2ec-11e7-8844-40413a6f5479.png)
But using the hotkey for profile switcher does visually loop through the selection, nothing happens with the sound output.

I assume this is related to #66

**Comment by thunderschnozzle** [comment]
I'm having the same issue. I have a 3.5mm headphones (HyperX CloudX Pro) connected to an external sound card (a built-in sound card in the Sades W10 Anubis' Staff headset holder), which, in turn, is connected to my PC using a USB plug. I have them set up along with a Bose stereo PC speakers. It looks just like azatoth's picture (minus the name of the headset of course).
I'm getting the same outcome as azatoth. That is, using the profile switcher hotkey seems to visually cycle through the USB headset, but no sound comes out

I think the source of the problem is the extension itself, but, unfortunately, I don't have the knowledge required to fix it

**Comment by corebots** [comment]
yes looks like related to my issue with a USB soundcard (Tascam US-100) mentioned in bug #66 already closed :(
