### ISSUE TITLE
Fills journalctl with errors

### ISSUE THREAD

**Issue by georgelemental** [aleho/gnome-shell-volume-mixer#99]
On `gnome-shell` 3.32, Ubuntu 19.04, this extensions fills `journalctl` with error messages. Representative sample:

```
== Stack trace for context 0x563349ddc1e0 ==
#0   56334e77e288 i   resource:///org/gnome/shell/ui/status/volume.js:104 (7
#1   7fff7f5912b0 b   resource:///org/gnome/shell/ui/status/volume.js:293 (7
#2   56334e77e200 i   /home/jules/.local/share/gnome-shell/extensions/shell-
#3   7fff7f592610 b   self-hosted:979 (7fe29ce50c10 @ 440)
```

```
Object St.BoxLayout (0x56334a67aa80), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

**Comment by aleho** [comment]
I can reproduce this when I reload the extension (`gnome-shell-extension-tool -r shell-volume-mixer@derhofbauer.at`). It doesn't happen after a fresh login for me.

This reason seems to be that a lot of signals never get unbound in shell because they didn't think anyone would extend the volume controls.

**Comment by aleho** [comment]
@georgelemental Does the latest commit to master fix it for you?

If not, could you please provide a complete sample, the one above seems cut off, missing the file and line number.

E.g.
```
Apr 22 19:49:30 mobian gnome-shell[4343]: Object St.DrawingArea (0x55b868145570), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: == Stack trace for context 0x55b865a3a2e0 ==
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #0   7fff815ca370 b   resource:///org/gnome/shell/ui/barLevel.js:44 (7fe4437c44c0 @ 117)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #1   7fff815ca420 b   resource:///org/gnome/shell/ui/status/volume.js:139 (7fe4434879d0 @ 99)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #2   7fff815ca4f0 b   self-hosted:979 (7fe4437508b0 @ 440)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #3   55b865da6750 i   resource:///org/gnome/shell/ui/status/volume.js:119 (7fe4434878b0 @ 164)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #4   55b865da66b0 i   /home/alex/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:155 (7fe441962ee0 @ 27)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #5   7fff815ccce0 b   self-hosted:979 (7fe4437508b0 @ 440)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #6   7fff815ccdd0 b   resource:///org/gnome/gjs/modules/signals.js:142 (7fe443acb8b0 @ 386)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #7   55b865da65b8 i   resource:///org/gnome/shell/ui/slider.js:158 (7fe44348dd30 @ 531)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #8   55b865da6530 i   resource:///org/gnome/shell/ui/slider.js:163 (7fe44348ddc0 @ 20)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #9   7fff815ce420 b   self-hosted:979 (7fe4437508b0 @ 440)
Apr 22 19:49:30 mobian gnome-shell[4343]: st_drawing_area_queue_repaint: assertion 'ST_IS_DRAWING_AREA (area)' failed
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: == Stack trace for context 0x55b865a3a2e0 ==
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #0   7fff815ca370 b   resource:///org/gnome/shell/ui/barLevel.js:44 (7fe4437c44c0 @ 117)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #1   7fff815ca420 b   resource:///org/gnome/shell/ui/status/volume.js:139 (7fe4434879d0 @ 99)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #2   7fff815ca4f0 b   self-hosted:979 (7fe4437508b0 @ 440)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #3   55b865da6750 i   resource:///org/gnome/shell/ui/status/volume.js:119 (7fe4434878b0 @ 164)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #4   55b865da66b0 i   /home/alex/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:155 (7fe441962ee0 @ 27)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #5   7fff815ccce0 b   self-hosted:979 (7fe4437508b0 @ 440)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #6   7fff815ccdd0 b   resource:///org/gnome/gjs/modules/signals.js:142 (7fe443acb8b0 @ 386)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #7   55b865da65b8 i   resource:///org/gnome/shell/ui/slider.js:158 (7fe44348dd30 @ 531)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #8   55b865da6530 i   resource:///org/gnome/shell/ui/slider.js:163 (7fe44348ddc0 @ 20)
Apr 22 19:49:30 mobian org.gnome.Shell.desktop[4343]: #9   7fff815ce420 b   self-hosted:979 (7fe4437508b0 @ 440)
```

**Comment by dantob** [comment]
`May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation gnome-shell[591]: Object St.BoxLayout (0x563005d8fc60), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: == Stack trace for context 0x5630056a0210 ==
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #0   7ffe9777dcc0 b   resource:///org/gnome/shell/ui/status/volume.js:96 (7f112cc8bc10 @ 49)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #1   7ffe9777dd80 b   resource:///org/gnome/shell/ui/status/volume.js:276 (7f112cc92670 @ 259)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #2   7ffe9777de20 b   /home/daniel/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:426 (7f110dd4eee0 @ 91)
May 02 22:22:31 abberation org.gnome.Shell.desktop[591]: #3   7ffe9777def0 b   self-hosted:979 (7f112ce513a0 @ 440)
May 02 22:22:31 abberation gnome-shell[591]: Object St.BoxLayout (0x56300a031100), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
`

**Comment by georgelemental** [comment]
There is a different error now (whenever the volume slider is used):
```
gnome-shell[6876]: JS ERROR: ReferenceError: GLib is not defined
                   _sliderChanged/this._notifyVolumeChangeId<@resource:///org/gnome/shell/ui/status/volume.js:139:17
```

**Comment by georgelemental** [comment]
This appears to have been fixed now.

**Comment by aleho** [comment]
Cannot reproduce either and also reloading of extensions has been removed from GNOME because "never actually worked", so 🤷‍♂️.

Thanks for your feedback.
